export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";
export const USER_LOGOUT = "USER_LOGOUT";

export const TOPIC_FETCH = "TOPIC_FETCH";
export const TOPIC_FETCH_SUCCESS = "TOPIC_FETCH_SUCCESS";

//Signup
export const USER_SIGNUP = "USER_SIGNUP";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAILURE = "USER_SIGNUP_FAILURE";

//Forum data
export const CREATE_FORUM = "CREATE_FORUM";
export const CREATE_FORUM_SUCCESS = "CREATE_FORUM_SUCCESS";
export const CREATE_FORUM_FAILURE = "CREATE_FORUM_FAILURE";

export const POST_FETCH = "POST_FETCH";
export const POST_FETCH_SUCCESS = "POST_FETCH_SUCCESS";

export const CREATE_TOPIC = "CREATE_TOPIC";
export const CREATE_TOPIC_SUCCESS = "CREATE_TOPIC_SUCCESS";
export const CREATE_TOPIC_FAILURE = "CREATE_TOPIC_FAILURE";

export const REPLAY_FETCH = "REPLAY_FETCH";
export const REPLAY_FETCH_SUCCESS = "REPLAY_FETCH_SUCCESS";

export const CREATE_REPLAY = "CREATE_REPLAY";
export const CREATE_REPLAY_SUCCESS = "CREATE_REPLAY_SUCCESS";
export const CREATE_REPLAY_FAILURE = "CREATE_REPLAY_FAILURE";

export const RECENT_TOPIC_FETCH = "RECENT_TOPIC_FETCH";
export const RECENT_TOPIC_FETCH_SUCCESS = "RECENT_TOPIC_FETCH_SUCCESS";

export const REPLY_DELETE = "REPLY_DELETE";
export const REPLY_DELETE_SUCCESS = "REPLY_DELETE_SUCCESS";
export const REPLY_DELETE_FAILURE = "REPLY_DELETE_FAILURE";
